"""Init migration

Revision ID: be5781c92ce0
Revises: 
Create Date: 2024-12-18 08:44:40.431956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be5781c92ce0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('user_hash')
    )
    op.create_index(op.f('ix_users_user_hash'), 'users', ['user_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_hash'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
